package main

import (
	"fmt"
	"strings"
)

// seedBook is one curated catalog entry. Title+Author drive a precise Google
// Books query (avoids the "obscure edition" bloat that plain-text search causes);
// ISBN, when set, is tried first for an exact canonical match.
type seedBook struct {
	Title  string
	Author string
	ISBN   string // ISBN-13, optional
}

// cacheKey is the stable disk-cache key for this entry.
func (s seedBook) cacheKey() string {
	if s.ISBN != "" {
		return "isbn:" + s.ISBN
	}
	return strings.ToLower(fmt.Sprintf("%s|%s", s.Title, s.Author))
}

// booklist is the curated set of popular titles. Spread across genres so the
// catalog, categories, and book-detail pages all look rich for the demo.
var booklist = []seedBook{
	// ── Modern literary / contemporary fiction ─────────────────────────────
	{Title: "The Midnight Library", Author: "Matt Haig"},
	{Title: "A Little Life", Author: "Hanya Yanagihara"},
	{Title: "Normal People", Author: "Sally Rooney"},
	{Title: "Conversations with Friends", Author: "Sally Rooney"},
	{Title: "Beautiful World, Where Are You", Author: "Sally Rooney"},
	{Title: "The Goldfinch", Author: "Donna Tartt"},
	{Title: "The Secret History", Author: "Donna Tartt"},
	{Title: "Where the Crawdads Sing", Author: "Delia Owens"},
	{Title: "Little Fires Everywhere", Author: "Celeste Ng"},
	{Title: "Everything I Never Told You", Author: "Celeste Ng"},
	{Title: "The Vanishing Half", Author: "Brit Bennett"},
	{Title: "Pachinko", Author: "Min Jin Lee"},
	{Title: "A Gentleman in Moscow", Author: "Amor Towles"},
	{Title: "The Lincoln Highway", Author: "Amor Towles"},
	{Title: "Rules of Civility", Author: "Amor Towles"},
	{Title: "The Overstory", Author: "Richard Powers"},
	{Title: "Lessons in Chemistry", Author: "Bonnie Garmus"},
	{Title: "Tomorrow, and Tomorrow, and Tomorrow", Author: "Gabrielle Zevin"},
	{Title: "Demon Copperhead", Author: "Barbara Kingsolver"},
	{Title: "The Poisonwood Bible", Author: "Barbara Kingsolver"},
	{Title: "Cloud Cuckoo Land", Author: "Anthony Doerr"},
	{Title: "All the Light We Cannot See", Author: "Anthony Doerr"},
	{Title: "The Nightingale", Author: "Kristin Hannah"},
	{Title: "The Four Winds", Author: "Kristin Hannah"},
	{Title: "Eleanor Oliphant Is Completely Fine", Author: "Gail Honeyman"},
	{Title: "A Man Called Ove", Author: "Fredrik Backman"},
	{Title: "Anxious People", Author: "Fredrik Backman"},
	{Title: "The Seven Husbands of Evelyn Hugo", Author: "Taylor Jenkins Reid"},
	{Title: "Daisy Jones & The Six", Author: "Taylor Jenkins Reid"},
	{Title: "Malibu Rising", Author: "Taylor Jenkins Reid"},
	{Title: "Klara and the Sun", Author: "Kazuo Ishiguro"},
	{Title: "Never Let Me Go", Author: "Kazuo Ishiguro"},
	{Title: "The Remains of the Day", Author: "Kazuo Ishiguro"},
	{Title: "Circe", Author: "Madeline Miller"},
	{Title: "The Song of Achilles", Author: "Madeline Miller"},
	{Title: "The Kite Runner", Author: "Khaled Hosseini"},
	{Title: "A Thousand Splendid Suns", Author: "Khaled Hosseini"},
	{Title: "The Help", Author: "Kathryn Stockett"},
	{Title: "The Book Thief", Author: "Markus Zusak"},
	{Title: "Life of Pi", Author: "Yann Martel"},

	// ── Classics ───────────────────────────────────────────────────────────
	{Title: "Pride and Prejudice", Author: "Jane Austen"},
	{Title: "Sense and Sensibility", Author: "Jane Austen"},
	{Title: "Emma", Author: "Jane Austen"},
	{Title: "Jane Eyre", Author: "Charlotte Bronte"},
	{Title: "Wuthering Heights", Author: "Emily Bronte"},
	{Title: "Great Expectations", Author: "Charles Dickens"},
	{Title: "A Tale of Two Cities", Author: "Charles Dickens"},
	{Title: "Oliver Twist", Author: "Charles Dickens"},
	{Title: "The Great Gatsby", Author: "F. Scott Fitzgerald"},
	{Title: "Tender Is the Night", Author: "F. Scott Fitzgerald"},
	{Title: "To Kill a Mockingbird", Author: "Harper Lee"},
	{Title: "Of Mice and Men", Author: "John Steinbeck"},
	{Title: "The Grapes of Wrath", Author: "John Steinbeck"},
	{Title: "East of Eden", Author: "John Steinbeck"},
	{Title: "Nineteen Eighty-Four", Author: "George Orwell"},
	{Title: "Animal Farm", Author: "George Orwell"},
	{Title: "Brave New World", Author: "Aldous Huxley"},
	{Title: "Fahrenheit 451", Author: "Ray Bradbury"},
	{Title: "The Martian Chronicles", Author: "Ray Bradbury"},
	{Title: "Catch-22", Author: "Joseph Heller"},
	{Title: "Slaughterhouse-Five", Author: "Kurt Vonnegut"},
	{Title: "Cat's Cradle", Author: "Kurt Vonnegut"},
	{Title: "The Catcher in the Rye", Author: "J. D. Salinger"},
	{Title: "Lord of the Flies", Author: "William Golding"},
	{Title: "Moby-Dick", Author: "Herman Melville"},
	{Title: "The Adventures of Huckleberry Finn", Author: "Mark Twain"},
	{Title: "The Adventures of Tom Sawyer", Author: "Mark Twain"},
	{Title: "Frankenstein", Author: "Mary Shelley"},
	{Title: "Dracula", Author: "Bram Stoker"},
	{Title: "The Picture of Dorian Gray", Author: "Oscar Wilde"},
	{Title: "Crime and Punishment", Author: "Fyodor Dostoevsky"},
	{Title: "The Brothers Karamazov", Author: "Fyodor Dostoevsky"},
	{Title: "Anna Karenina", Author: "Leo Tolstoy"},
	{Title: "War and Peace", Author: "Leo Tolstoy"},
	{Title: "One Hundred Years of Solitude", Author: "Gabriel Garcia Marquez"},
	{Title: "Love in the Time of Cholera", Author: "Gabriel Garcia Marquez"},
	{Title: "Beloved", Author: "Toni Morrison"},
	{Title: "The Bluest Eye", Author: "Toni Morrison"},
	{Title: "Their Eyes Were Watching God", Author: "Zora Neale Hurston"},
	{Title: "Invisible Man", Author: "Ralph Ellison"},
	{Title: "The Sun Also Rises", Author: "Ernest Hemingway"},
	{Title: "The Old Man and the Sea", Author: "Ernest Hemingway"},
	{Title: "A Farewell to Arms", Author: "Ernest Hemingway"},
	{Title: "Their Heart Is a Lonely Hunter", Author: "Carson McCullers"},

	// ── Fantasy ──────────────────────────────────────────────────────────────
	{Title: "Harry Potter and the Sorcerer's Stone", Author: "J. K. Rowling"},
	{Title: "Harry Potter and the Chamber of Secrets", Author: "J. K. Rowling"},
	{Title: "Harry Potter and the Prisoner of Azkaban", Author: "J. K. Rowling"},
	{Title: "Harry Potter and the Goblet of Fire", Author: "J. K. Rowling"},
	{Title: "Harry Potter and the Order of the Phoenix", Author: "J. K. Rowling"},
	{Title: "Harry Potter and the Half-Blood Prince", Author: "J. K. Rowling"},
	{Title: "Harry Potter and the Deathly Hallows", Author: "J. K. Rowling"},
	{Title: "The Hobbit", Author: "J. R. R. Tolkien"},
	{Title: "The Fellowship of the Ring", Author: "J. R. R. Tolkien"},
	{Title: "The Two Towers", Author: "J. R. R. Tolkien"},
	{Title: "The Return of the King", Author: "J. R. R. Tolkien"},
	{Title: "The Silmarillion", Author: "J. R. R. Tolkien"},
	{Title: "A Game of Thrones", Author: "George R. R. Martin"},
	{Title: "A Clash of Kings", Author: "George R. R. Martin"},
	{Title: "A Storm of Swords", Author: "George R. R. Martin"},
	{Title: "The Name of the Wind", Author: "Patrick Rothfuss"},
	{Title: "The Wise Man's Fear", Author: "Patrick Rothfuss"},
	{Title: "The Way of Kings", Author: "Brandon Sanderson"},
	{Title: "Words of Radiance", Author: "Brandon Sanderson"},
	{Title: "Mistborn: The Final Empire", Author: "Brandon Sanderson"},
	{Title: "The Lion, the Witch and the Wardrobe", Author: "C. S. Lewis"},
	{Title: "The Eye of the World", Author: "Robert Jordan"},
	{Title: "Assassin's Apprentice", Author: "Robin Hobb"},
	{Title: "The Color of Magic", Author: "Terry Pratchett"},
	{Title: "Good Omens", Author: "Terry Pratchett"},
	{Title: "American Gods", Author: "Neil Gaiman"},
	{Title: "Neverwhere", Author: "Neil Gaiman"},
	{Title: "The Ocean at the End of the Lane", Author: "Neil Gaiman"},
	{Title: "Stardust", Author: "Neil Gaiman"},
	{Title: "The Night Circus", Author: "Erin Morgenstern"},
	{Title: "A Court of Thorns and Roses", Author: "Sarah J. Maas"},
	{Title: "Throne of Glass", Author: "Sarah J. Maas"},
	{Title: "The Priory of the Orange Tree", Author: "Samantha Shannon"},
	{Title: "Piranesi", Author: "Susanna Clarke"},
	{Title: "Jonathan Strange & Mr Norrell", Author: "Susanna Clarke"},
	{Title: "The Fifth Season", Author: "N. K. Jemisin"},
	{Title: "Babel", Author: "R. F. Kuang"},
	{Title: "The Poppy War", Author: "R. F. Kuang"},

	// ── Science fiction ──────────────────────────────────────────────────────
	{Title: "Dune", Author: "Frank Herbert"},
	{Title: "Dune Messiah", Author: "Frank Herbert"},
	{Title: "Children of Dune", Author: "Frank Herbert"},
	{Title: "Foundation", Author: "Isaac Asimov"},
	{Title: "I, Robot", Author: "Isaac Asimov"},
	{Title: "The Caves of Steel", Author: "Isaac Asimov"},
	{Title: "Ender's Game", Author: "Orson Scott Card"},
	{Title: "Hyperion", Author: "Dan Simmons"},
	{Title: "Neuromancer", Author: "William Gibson"},
	{Title: "Snow Crash", Author: "Neal Stephenson"},
	{Title: "The Left Hand of Darkness", Author: "Ursula K. Le Guin"},
	{Title: "A Wizard of Earthsea", Author: "Ursula K. Le Guin"},
	{Title: "Do Androids Dream of Electric Sheep?", Author: "Philip K. Dick"},
	{Title: "The Man in the High Castle", Author: "Philip K. Dick"},
	{Title: "The Martian", Author: "Andy Weir"},
	{Title: "Project Hail Mary", Author: "Andy Weir"},
	{Title: "Artemis", Author: "Andy Weir"},
	{Title: "Ready Player One", Author: "Ernest Cline"},
	{Title: "The Three-Body Problem", Author: "Cixin Liu"},
	{Title: "The Dark Forest", Author: "Cixin Liu"},
	{Title: "Leviathan Wakes", Author: "James S. A. Corey"},
	{Title: "Children of Time", Author: "Adrian Tchaikovsky"},
	{Title: "A Fire Upon the Deep", Author: "Vernor Vinge"},
	{Title: "Recursion", Author: "Blake Crouch"},
	{Title: "Dark Matter", Author: "Blake Crouch"},
	{Title: "The Handmaid's Tale", Author: "Margaret Atwood"},
	{Title: "Oryx and Crake", Author: "Margaret Atwood"},
	{Title: "Station Eleven", Author: "Emily St. John Mandel"},
	{Title: "Sea of Tranquility", Author: "Emily St. John Mandel"},

	// ── Mystery / thriller ───────────────────────────────────────────────────
	{Title: "Gone Girl", Author: "Gillian Flynn"},
	{Title: "Sharp Objects", Author: "Gillian Flynn"},
	{Title: "The Girl with the Dragon Tattoo", Author: "Stieg Larsson"},
	{Title: "The Girl on the Train", Author: "Paula Hawkins"},
	{Title: "The Silent Patient", Author: "Alex Michaelides"},
	{Title: "The Da Vinci Code", Author: "Dan Brown"},
	{Title: "Angels & Demons", Author: "Dan Brown"},
	{Title: "The Thursday Murder Club", Author: "Richard Osman"},
	{Title: "The Guest List", Author: "Lucy Foley"},
	{Title: "Big Little Lies", Author: "Liane Moriarty"},
	{Title: "The Husband's Secret", Author: "Liane Moriarty"},
	{Title: "And Then There Were None", Author: "Agatha Christie"},
	{Title: "Murder on the Orient Express", Author: "Agatha Christie"},
	{Title: "The Murder of Roger Ackroyd", Author: "Agatha Christie"},
	{Title: "The Adventures of Sherlock Holmes", Author: "Arthur Conan Doyle"},
	{Title: "The Hound of the Baskervilles", Author: "Arthur Conan Doyle"},
	{Title: "The Reversal", Author: "Michael Connelly"},
	{Title: "The Lincoln Lawyer", Author: "Michael Connelly"},
	{Title: "Along Came a Spider", Author: "James Patterson"},
	{Title: "The Bourne Identity", Author: "Robert Ludlum"},
	{Title: "The Firm", Author: "John Grisham"},
	{Title: "A Time to Kill", Author: "John Grisham"},
	{Title: "The Pelican Brief", Author: "John Grisham"},
	{Title: "Mystic River", Author: "Dennis Lehane"},
	{Title: "Shutter Island", Author: "Dennis Lehane"},
	{Title: "In the Woods", Author: "Tana French"},
	{Title: "The Cuckoo's Calling", Author: "Robert Galbraith"},

	// ── Horror ───────────────────────────────────────────────────────────────
	{Title: "The Shining", Author: "Stephen King"},
	{Title: "It", Author: "Stephen King"},
	{Title: "The Stand", Author: "Stephen King"},
	{Title: "Misery", Author: "Stephen King"},
	{Title: "Pet Sematary", Author: "Stephen King"},
	{Title: "Carrie", Author: "Stephen King"},
	{Title: "11/22/63", Author: "Stephen King"},
	{Title: "Salem's Lot", Author: "Stephen King"},
	{Title: "Mexican Gothic", Author: "Silvia Moreno-Garcia"},
	{Title: "The Haunting of Hill House", Author: "Shirley Jackson"},
	{Title: "We Have Always Lived in the Castle", Author: "Shirley Jackson"},
	{Title: "Interview with the Vampire", Author: "Anne Rice"},
	{Title: "House of Leaves", Author: "Mark Z. Danielewski"},

	// ── Young adult ──────────────────────────────────────────────────────────
	{Title: "The Hunger Games", Author: "Suzanne Collins"},
	{Title: "Catching Fire", Author: "Suzanne Collins"},
	{Title: "Mockingjay", Author: "Suzanne Collins"},
	{Title: "The Ballad of Songbirds and Snakes", Author: "Suzanne Collins"},
	{Title: "The Fault in Our Stars", Author: "John Green"},
	{Title: "Looking for Alaska", Author: "John Green"},
	{Title: "The Perks of Being a Wallflower", Author: "Stephen Chbosky"},
	{Title: "The Maze Runner", Author: "James Dashner"},
	{Title: "Divergent", Author: "Veronica Roth"},
	{Title: "The Giver", Author: "Lois Lowry"},
	{Title: "Percy Jackson and the Lightning Thief", Author: "Rick Riordan"},
	{Title: "Eragon", Author: "Christopher Paolini"},
	{Title: "Twilight", Author: "Stephenie Meyer"},
	{Title: "The Hate U Give", Author: "Angie Thomas"},
	{Title: "Six of Crows", Author: "Leigh Bardugo"},
	{Title: "Shadow and Bone", Author: "Leigh Bardugo"},
	{Title: "Children of Blood and Bone", Author: "Tomi Adeyemi"},
	{Title: "They Both Die at the End", Author: "Adam Silvera"},

	// ── Romance ──────────────────────────────────────────────────────────────
	{Title: "It Ends with Us", Author: "Colleen Hoover"},
	{Title: "Verity", Author: "Colleen Hoover"},
	{Title: "Ugly Love", Author: "Colleen Hoover"},
	{Title: "Beach Read", Author: "Emily Henry"},
	{Title: "People We Meet on Vacation", Author: "Emily Henry"},
	{Title: "Book Lovers", Author: "Emily Henry"},
	{Title: "Red, White & Royal Blue", Author: "Casey McQuiston"},
	{Title: "The Hating Game", Author: "Sally Thorne"},
	{Title: "The Kiss Quotient", Author: "Helen Hoang"},
	{Title: "The Love Hypothesis", Author: "Ali Hazelwood"},
	{Title: "Outlander", Author: "Diana Gabaldon"},
	{Title: "Me Before You", Author: "Jojo Moyes"},
	{Title: "The Notebook", Author: "Nicholas Sparks"},
	{Title: "Bridgerton: The Duke and I", Author: "Julia Quinn"},

	// ── Nonfiction ───────────────────────────────────────────────────────────
	{Title: "Sapiens: A Brief History of Humankind", Author: "Yuval Noah Harari"},
	{Title: "Homo Deus", Author: "Yuval Noah Harari"},
	{Title: "Educated", Author: "Tara Westover"},
	{Title: "Becoming", Author: "Michelle Obama"},
	{Title: "Atomic Habits", Author: "James Clear"},
	{Title: "Thinking, Fast and Slow", Author: "Daniel Kahneman"},
	{Title: "Outliers", Author: "Malcolm Gladwell"},
	{Title: "The Tipping Point", Author: "Malcolm Gladwell"},
	{Title: "Blink", Author: "Malcolm Gladwell"},
	{Title: "Quiet: The Power of Introverts", Author: "Susan Cain"},
	{Title: "The Body Keeps the Score", Author: "Bessel van der Kolk"},
	{Title: "The Immortal Life of Henrietta Lacks", Author: "Rebecca Skloot"},
	{Title: "A Short History of Nearly Everything", Author: "Bill Bryson"},
	{Title: "A Brief History of Time", Author: "Stephen Hawking"},
	{Title: "Cosmos", Author: "Carl Sagan"},
	{Title: "The Selfish Gene", Author: "Richard Dawkins"},
	{Title: "Guns, Germs, and Steel", Author: "Jared Diamond"},
	{Title: "The Wright Brothers", Author: "David McCullough"},
	{Title: "Steve Jobs", Author: "Walter Isaacson"},
	{Title: "Born a Crime", Author: "Trevor Noah"},
	{Title: "When Breath Becomes Air", Author: "Paul Kalanithi"},
	{Title: "Man's Search for Meaning", Author: "Viktor E. Frankl"},
	{Title: "The Devil in the White City", Author: "Erik Larson"},
	{Title: "Into the Wild", Author: "Jon Krakauer"},
	{Title: "Into Thin Air", Author: "Jon Krakauer"},
	{Title: "Bad Blood", Author: "John Carreyrou"},
	{Title: "Just Mercy", Author: "Bryan Stevenson"},
	{Title: "The Warmth of Other Suns", Author: "Isabel Wilkerson"},
	{Title: "Caste: The Origins of Our Discontents", Author: "Isabel Wilkerson"},
	{Title: "The Power of Habit", Author: "Charles Duhigg"},
	{Title: "Range: Why Generalists Triumph", Author: "David Epstein"},

	// ── Children's / middle grade ───────────────────────────────────────────
	{Title: "Charlotte's Web", Author: "E. B. White"},
	{Title: "Where the Wild Things Are", Author: "Maurice Sendak"},
	{Title: "The Very Hungry Caterpillar", Author: "Eric Carle"},
	{Title: "Matilda", Author: "Roald Dahl"},
	{Title: "Charlie and the Chocolate Factory", Author: "Roald Dahl"},
	{Title: "The BFG", Author: "Roald Dahl"},
	{Title: "Wonder", Author: "R. J. Palacio"},
	{Title: "Holes", Author: "Louis Sachar"},
	{Title: "Bridge to Terabithia", Author: "Katherine Paterson"},
	{Title: "A Wrinkle in Time", Author: "Madeleine L'Engle"},
	{Title: "The Tale of Despereaux", Author: "Kate DiCamillo"},
	{Title: "Because of Winn-Dixie", Author: "Kate DiCamillo"},
	{Title: "Diary of a Wimpy Kid", Author: "Jeff Kinney"},
}
