// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1001
package book

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	"voxelprismatic/library-management-senior-project/db"
	"voxelprismatic/library-management-senior-project/web/common"
)

func formatShield(flag db.BookFmtFlag) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		switch flag {
		case db.BookFmtPaperback:
			templ_7745c5c3_Err = common.Shield("import_contacts", "Paperback", "var(--peach)", "var(--text)").Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		case db.BookFmtHardCover:
			templ_7745c5c3_Err = common.Shield("book_4", "Hard Cover", "var(--peach)", "var(--text)").Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		case db.BookFmtPhysicalAudio:
			templ_7745c5c3_Err = common.Shield("mobile_speaker", "Audio Player", "var(--teal)", "var(--text)").Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		case db.BookFmtDigitalBook:
			templ_7745c5c3_Err = common.Shield("text_snippet", "Kindle", "var(--green)", "var(--text)").Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		case db.BookFmtDigitalAudio:
			templ_7745c5c3_Err = common.Shield("audio_file", "Audible", "var(--sky)", "var(--text)").Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
